---
MD012: false  # Autorise les lignes vides consécutives (si tu préfères aérer)
MD013: false  # Désactive la règle de longueur de ligne (souvent pénible)
MD033: false  # Autorise le HTML (nécessaire pour redimensionner les images avec <img>)
