wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  min_auth_mode: WPA2

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${name} Hotspot"
    password: !secret esphome_ap_password

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_encryption_key
  custom_services: true
  homeassistant_services: true
  id: api_apiserver
  reboot_timeout: 15min

ota:
  - platform: esphome
    password: !secret esphome_ota_password

# Enable logging
logger:
  level: WARN

mdns:

web_server:
  port: 80
  # Optional: Customize the appearance or functionality
  version: 3 # Use version 3 for HA-Styling and sorting groups
  local: true # Include supporting JavaScript locally for offline access
