name: ESPHome Validation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: 🛒 Checkout du dépôt
        uses: actions/checkout@v6

      - name: 🔐 Créer un faux secrets.yaml
        run: |
          cp secrets.yaml.example secrets.yaml

      - name: 🔍 Détection et Validation des fichiers YAML
        run: |
          # On cherche tous les .yaml à la racine,
          # en excluant secrets.yaml et les fichiers d'exemple
          files=$(grep -l 'esphome:' *.yaml)

          echo "Fichiers détectés pour validation : $files"

          for file in $files; do
            echo "--- Validation de $file ---"
            # On utilise la commande 'config' d'esphome qui vérifie la syntaxe
            # sans générer le binaire complet
            docker run --rm -v "${PWD}":/config -w /config esphome/esphome:2026.4.2 config "$file"
          done
